### PR TITLE
addressed asserEquals deprected warning, changed to assertEqual

### PR DESCRIPTION
**Pull request by anthonylouisburns**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/64)

### CODE REVIEW

**Comment by katbusch** [comment]
Thanks for the clean up @anthonylouisburns!

**Comment by katbusch** [comment]
Looks like you have a minor lint issue from the change.  You can run `flake8` to lint locally for testing.

**Comment by katbusch** [comment]
Looks like there's an issue with coveralls.  No changes are needed on your end for that respect--I'll fix it on master.

Can you revert the changes to doppelganger_example_simple.ipynb though?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/64#-:-L6TSAV83cM97geY0kdd:b-vvi3zq)*

**Comment by anthonylouisburns** [comment]
@katbusch addressed the flake8 issue - not sure why I am getting a failure

Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Exited with code 2

**Comment by katbusch** [comment]
It's a problem with our coveralls config--nothing you did.  I'll fix it and merge this when it's fixed

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/64#-:-L6Tno1qKFELZ9FZUMS8:b-73cjgy)*

**Pull request merged**
