### PR TITLE
Marginal vehicles

### PR DESCRIPTION
**Pull request by nikisix**
Use the number of vehicles a household has as an additional marginal control to the solver for increased accuracy around transport variables.

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/41)

### CODE REVIEW

**Comment by katbusch** [comment]
Thanks @nikisix ! A few comments / questions

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[doppelganger/allocation.py, line 146 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts1vKINdLvguKFUFIX:-Kts1vKINdLvguKFUFIY:b-75pjk9) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L146)):*
> ```Python
>         allocation_inputs = [inputs.NUM_PEOPLE, inputs.NUM_VEHICLES]  # Hard-coded for now
>         # Prepend column name to bin name to prevent bin collision
>         hh_columns = list()
> ```

`hh_columns = []` is more pythonic

---

*[doppelganger/allocation.py, line 147 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts20XEBwY16ihTRdwV:-Kts20XEBwY16ihTRdwW:b-b1ysrl) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L147)):*
> ```Python
>         # Prepend column name to bin name to prevent bin collision
>         hh_columns = list()
>         for i in allocation_inputs:
> ```

`i` usually means an integer index.  If it's not an integer it should have a different name that explains what it is

---

*[doppelganger/allocation.py, line 196 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts3XqoqRtUz-SfbV7n:-Kts3XqoqRtUz-SfbV7o:b-fdo9nw) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L196)):*
> ```Python
>     def _format_data(households_data, persons_data):
>         hh_size = pandas.get_dummies(households_data[inputs.NUM_PEOPLE.name])
>         # Prepend column name to bin name to prevent bin collision
> ```

Can you create a helper for this so that you don't have to have the same code here and above?

---

*[doppelganger/inputs.py, line 86 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts4NJpDWePEANKECXx:-Kts4NJpDWePEANKECXy:bz729s2) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/inputs.py#L86)):*
> ```Python
> def num_people_discrete(num_people):
>     if is_blank(num_people) or int(num_people) == 0:  # match acs (can't have 0-person household)
>         return '0'  # UNKNOWN causing problems in the bayes-net segmenter
> ```

Can you explain what problems this causes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-:-Kts4wh1Ta1iofNUZDMd:b9v6397)*

**Comment by nikisix** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[doppelganger/allocation.py, line 146 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts1vKINdLvguKFUFIX:-KtsABvvR5j6bBBcncOj:b-896fix) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L146)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

`hh_columns = []` is more pythonic
</blockquote></details>

Done.

---

*[doppelganger/allocation.py, line 147 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts20XEBwY16ihTRdwV:-KtsB-hFyR80YoH5d0Qp:b-uprxw3) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L147)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

`i` usually means an integer index.  If it's not an integer it should have a different name that explains what it is
</blockquote></details>

It's true. 

if you_like(a_input):
    Done.

---

*[doppelganger/allocation.py, line 196 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts3XqoqRtUz-SfbV7n:-KtsJYooAu3CLHDiMyXB:b-896fix) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/allocation.py#L196)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Can you create a helper for this so that you don't have to have the same code here and above?
</blockquote></details>

Done.

---

*[doppelganger/inputs.py, line 86 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts4NJpDWePEANKECXx:-KtvJkAgOb_t7iSyfWrZ:bivsn8t) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Can you explain what problems this causes?
</blockquote></details>

The bin-values of the variables we're segmenting on become json keys and are run through a sorter before being written out. The None type throws a sorting error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by nikisix** [comment]
Maybe we can give coveralls another shot today so I can figure out what needs tests around it.

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-:-KtvQ1mbypZr3y-Zkopo:b-6stjw)*

**Comment by katbusch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[doppelganger/allocation.py, line 148 at r3](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-KtvjhIPjMyXOFzVEYum:-KtvjhIPjMyXOFzVEYun:bp14uye) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/df4e51d7a5b1f707f304915ff80a54d7b42710d7/doppelganger/allocation.py#L148)):*
> ```Python
>         hh_columns = []
>         for a_input in allocation_inputs:
>             hh_columns += ['_'.join([a_input.name, val]) for val in list(a_input.possible_values)]
> ```

can you use `_str_broadcast` here too?

---

*[doppelganger/inputs.py, line 86 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts4NJpDWePEANKECXx:-Ktvj3cVtmbX8iAI0Rtw:bfe0fbl) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

The bin-values of the variables we're segmenting on become json keys and are run through a sorter before being written out. The None type throws a sorting error.
</blockquote></details>

So the problem is in `BayesianNetworkModel.to_json`? Can you please file an issue with an exception trace?

---

*[test/test_allocation.py, line 32 at r3](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Ktvjof8OIQueVcrDfDu:-Ktvjof8OIQueVcrDfDv:b14trk3) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/df4e51d7a5b1f707f304915ff80a54d7b42710d7/test/test_allocation.py#L32)):*
> ```Python
>         households.to_csv.assert_called_once_with('households_file')
> 
>     def test__str_broadcast(self):
> ```

Thanks for adding a test! We generally don't test private methods directly.  Can you rework this test to use the public-facing API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by nikisix** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/test_allocation.py, line 32 at r3](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Ktvjof8OIQueVcrDfDu:-KtwI283-EBdg7hrDAsX:b-ohtqk) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/df4e51d7a5b1f707f304915ff80a54d7b42710d7/test/test_allocation.py#L32)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Thanks for adding a test! We generally don't test private methods directly.  Can you rework this test to use the public-facing API?
</blockquote></details>

Wish I would've seen this. Yea I'll switch it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by nikisix** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[doppelganger/allocation.py, line 148 at r3](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-KtvjhIPjMyXOFzVEYum:-KtwIKytcHoHD1cUVSft:b-rbc1l3) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/df4e51d7a5b1f707f304915ff80a54d7b42710d7/doppelganger/allocation.py#L148)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

can you use `_str_broadcast` here too?
</blockquote></details>

Lol yea, meant to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by nikisix** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 86 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts4NJpDWePEANKECXx:-KtwQzh1IezVh6NSfpc9:b-m0m17w) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

So the problem is in `BayesianNetworkModel.to_json`? Can you please file an issue with an exception trace?
</blockquote></details>

Filed.
https://github.com/sidewalklabs/doppelganger/issues/42

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by katbusch** [comment]
Great, good to go once the test is fixed but I have a question below

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 86 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Kts4NJpDWePEANKECXx:-KtwXUMSIYxdWnZSgSGE:b-9755fn) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/789fb1db0c6f96b1fb5f1ec030b0fd9c9be3700a/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

Filed.
https://github.com/sidewalklabs/doppelganger/issues/42
</blockquote></details>

Thank you!

---

*[doppelganger/inputs.py, line 86 at r5](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-KtwXIMNtY_6tny6eRKo:-KtwXIMNtY_6tny6eRKp:b-pioznb) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/b06adf06dcac42ca217f39c54990ae7a796ebacc/doppelganger/inputs.py#L86)):*
> ```Python
> def num_people_discrete(num_people):
>     if is_blank(num_people):
>         return UNKNOWN
> ```

Do you need to change this for it to work?  If it needs to be the other way for now you can leave it like that but add a link to the issue with a TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-:-KtwXWWvavkp2X9r0tEV:bnvm9cg)*

**Comment by nikisix** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 86 at r5](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-KtwXIMNtY_6tny6eRKo:-Ktw_K5uxLrh_m4d_tWl:bgnj46e) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/b06adf06dcac42ca217f39c54990ae7a796ebacc/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Do you need to change this for it to work?  If it needs to be the other way for now you can leave it like that but add a link to the issue with a TODO
</blockquote></details>

I reverted it for now, so it won't break on a puma that contains null household numbers. You'll see it with the test push coming up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Comment by katbusch** [comment]
:lgtm:
Just one suggestion for future

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[doppelganger/inputs.py, line 86 at r5](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-KtwXIMNtY_6tny6eRKo:-Ku1CQOnaTwy2qqW5SzV:b-ybtbf9) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/b06adf06dcac42ca217f39c54990ae7a796ebacc/doppelganger/inputs.py#L86)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

I reverted it for now, so it won't break on a puma that contains null household numbers. You'll see it with the test push coming up.
</blockquote></details>

Can you link to the issue with and add a TODO to fix?

---

*[test/test_allocation.py, line 49 at r7](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Ku1CjD4-aEFRmkHkA_R:-Ku1CjD4-aEFRmkHkA_S:b-o1rr7x) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/705461447111beefdc1850d85070afdf5c0ddf51/test/test_allocation.py#L49)):*
> ```Python
> 
>     def _mock_tract_data(self):
>         return pandas.DataFrame([
> ```

In the future, we should try to make our test cases the minimal they need to be for the case we're testing.  This looks a bit large and we probably could have done several smaller test cases for different edge cases instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-:-Ku1CzW2ooyM22R06nGS:b3mabc1)*

**Comment by nikisix** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[test/test_allocation.py, line 49 at r7](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41#-Ku1CjD4-aEFRmkHkA_R:-Ku1FvEX-EerWHoDvJ6y:b3jjtra) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/705461447111beefdc1850d85070afdf5c0ddf51/test/test_allocation.py#L49)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

In the future, we should try to make our test cases the minimal they need to be for the case we're testing.  This looks a bit large and we probably could have done several smaller test cases for different edge cases instead
</blockquote></details>

Definitely, the tricky part here is that most of the major machinery in allocation.py are private methods  (_allocate_households and _format_data), and our goal was to test these methods using the public api if I recall.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/41)*

**Pull request merged**
