### PR TITLE
Add work-status and educational-attainment nodes to person model

### PR DESCRIPTION
**Pull request by nikisix**
Side note: temporarily removed segmentation due to growing model size. In general, do we want to use segmentation for first round pop-synths? If so, what to segment on if not the default age and household size.

Do we need to update populationgen.Population.generate to use other fields, or are the person.age, person.sex and household.num_people fields sufficient? 

Example model output from running on a puma 29-00901:
[models.zip](https://github.com/sidewalklabs/doppelganger/files/1283646/models.zip)

Here's my first guess at the expanded model person_bn.json:
```{
  "type": "person",
  "nodes": [
    "age",
    "sex",
    "income",
    "working",
    "education"
  ],
  "edges": {
    "age": [
      "income"
    ],
    "sex": [
      "income",
      "working"
    ],
    "working": [
        "income"
    ],
    "education": [
        "income"
    ]
  }
}
```
Can also see an argument for an arrow from education (attainment) to working (work status)

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/39)

### CODE REVIEW

**Comment by katbusch** [comment]
Thanks for adding these!

> removed segmentation due to growing model size
Can you explain exactly what you mean by this?

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 103 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtShHlLHVRxQJS31r36:-KtShHlLHVRxQJS31r37:bmdol31) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/bed5f49a3090b326c72bbc4ffb2b5b8ed4e7e752/doppelganger/inputs.py#L103)):*
> ```Python
>         return 'under-16'
>     if code == '1' or code == '2' or code == '4' or code == '5':
>         return 'Y'
> ```

How about something a little more descriptive than 'Y' and 'N'? 'employed' and 'unemployed'?  And would be great if those were defined like:
```
class EmploymentStatus(object):
  UNDER_16 = 'under16'
  UNEMPLOYED = 'unemployed'
...
```
 

---

*[doppelganger/inputs.py, line 153 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtShofBPzrSS-vv9aXh:-KtShofBPzrSS-vv9aXi:b-kbniui) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/bed5f49a3090b326c72bbc4ffb2b5b8ed4e7e752/doppelganger/inputs.py#L153)):*
> ```Python
>         return 'bachelors-degree'
>     if code == '22' or code == '23' or code == '24':
>         return 'advanced-degree'
> ```

Same here for constant definitions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtSh8vlTPuJ4nTWTxI4:bfj7g7q)*

**Comment by katbusch** [comment]
> removed segmentation due to growing model size

Can you explain exactly what you mean by this?

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtSi12rfuxuEYUGijRc:banw233)*

**Comment by nikisix** [comment]
Definitely -- Sending None as my segmentation functions (person_segmenter below)  to the create_bayes_net.
I.e.
```    # Write the persons bayes net to disk
    person_training_data = SegmentedData.from_data(
        cleaned_data=persons_data,
        fields=list(configuration.person_fields),
        weight_field=inputs.PERSON_WEIGHT.name,
        segmenter=person_segmenter
    )
    person_model = BayesianNetworkModel.train(
        input_data=person_training_data,
        structure=configuration.person_structure,
        fields=configuration.person_fields
    )
```
Was wondering what/if segmenters make the most sense for our KC synth. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 103 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtShHlLHVRxQJS31r36:-KtT8ZNWt_bc9J9o9bYN:b-lxijsx) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/bed5f49a3090b326c72bbc4ffb2b5b8ed4e7e752/doppelganger/inputs.py#L103)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

How about something a little more descriptive than 'Y' and 'N'? 'employed' and 'unemployed'?  And would be great if those were defined like:
```
class EmploymentStatus(object):
  UNDER_16 = 'under16'
  UNEMPLOYED = 'unemployed'
...
```
 
</blockquote></details>

This was prescient as I'm in the process of doing that for some other variables right now as well :) . Good suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtT8qhcmKG3YN6uVB6a:buh8fv)*

**Comment by nikisix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 103 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtShHlLHVRxQJS31r36:-KtTA2-u1VH4-AxM4QOK:b-xjq841) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/bed5f49a3090b326c72bbc4ffb2b5b8ed4e7e752/doppelganger/inputs.py#L103)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

This was prescient as I'm in the process of doing that for some other variables right now as well :) . Good suggestion!
</blockquote></details>

Also, am going with '(not)working' as '(un)employed' has strict census definitions around it and is technically a subset of what's in working.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39)*

**Comment by katbusch** [comment]
Ask @alexeisw which segmentations he'd like to see.

Still not sure what you mean by "growing model size".  Is segmentation making it slow?

It's okay to send None by just leaving the segmenter argument out

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtTAYUq-Cd33fNvO3fg:b-hvv3wm)*

**Comment by nikisix** [comment]
2. Not slow, but the bayesian model output grows to keep track of much more conditional probs when you segment, and I was just keeping it more interpretable so I can analyze the outputs easier in the meantime. 

1. I'll be sure and ask @alexeisw what we're going with for the production run though.

3. Yep, ultimately, I'd like to allow users to pass a function in or at least define their own in the runner script. Still thinking it through.. ideas welcome.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtTBcWpuj4fyHB7ici1:b-u115uk)*

**Comment by katbusch** [comment]
I see! That makes sense.  A couple more comments

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 126 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVLW238doLhMNzsHf:-KtlVLW238doLhMNzsHg:brht74l) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/inputs.py#L126)):*
> ```Python
> def educational_attainment(code):
>     ''' Educational attainment (SCHL)
>         bb .N/A (less than 3 years old)
> ```

Can you explain that these are the PUMS codes (and maybe the year if they're allowed to change)

---

*[doppelganger/scripts/download_allocate_generate.py, line 24 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVSfFrXsffbBdxcbw:-KtlVSfFrXsffbBdxcbx:b-7tupg3) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/scripts/download_allocate_generate.py#L24)):*
> ```Python
> 
> 
> def person_segmenter(x): return None  # x[inputs.AGE.name]
> ```

So instead of changing these to return None, you can just remove them completely and you'll get the same effect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtlVgu1GfgvZbrkSO6a:bpcainw)*

**Comment by katbusch** [comment]
Oh and please add tests for the new code!

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-KtlVoFb8iKaEl4bmWdS:bc97h0l)*

**Comment by nikisix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[doppelganger/inputs.py, line 153 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtShofBPzrSS-vv9aXh:-KtrQAznncu54GVrLCn1:b-896fix) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/bed5f49a3090b326c72bbc4ffb2b5b8ed4e7e752/doppelganger/inputs.py#L153)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Same here for constant definitions
</blockquote></details>

Done.

---

*[doppelganger/inputs.py, line 126 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVLW238doLhMNzsHf:-KtrObI2AQUBqTZpwR4l:b-o4ly33) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/inputs.py#L126)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Can you explain that these are the PUMS codes (and maybe the year if they're allowed to change)
</blockquote></details>

Good call! Done.

---

*[doppelganger/scripts/download_allocate_generate.py, line 24 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVSfFrXsffbBdxcbw:-KtrQF_7IdHOlvpfA2DT:bbloyed) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/scripts/download_allocate_generate.py#L24)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

So instead of changing these to return None, you can just remove them completely and you'll get the same effect
</blockquote></details>

Got feedback from Alexei, we're keeping them in. Cleaned up the None vals and comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39)*

**Comment by katbusch** [comment]
Ping on tests :)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doppelganger/scripts/download_allocate_generate.py, line 24 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVSfFrXsffbBdxcbw:-KtvlnvxfO1q_qCkinC2:bdp6rxg) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/scripts/download_allocate_generate.py#L24)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

Got feedback from Alexei, we're keeping them in. Cleaned up the None vals and comments
</blockquote></details>

Why are you keeping them in?  The functionality will remain the same if you remove these functions and the code will be cleaner

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-Ktvm6-78-S7pIg4wvp4:b-qjxasa)*

**Comment by nikisix** [comment]
Yep, just finished writing allocator's test for the `margina-vehicles` branch. Diving into this guy today.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doppelganger/scripts/download_allocate_generate.py, line 24 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVSfFrXsffbBdxcbw:-Ku0_9JV82vH4cVzcS6w:bp1i32i) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/scripts/download_allocate_generate.py#L24)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Why are you keeping them in?  The functionality will remain the same if you remove these functions and the code will be cleaner
</blockquote></details>

I should clarify, Alexei said we will want to employ segmentation for now at least. So I'm back to the original: 
`def person_segmenter(x): return x[inputs.AGE.name]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-Ku0_eTghgpAnI8nXldE:b-wcr6h4)*

**Comment by nikisix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doppelganger/scripts/download_allocate_generate.py, line 24 at r2](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-KtlVSfFrXsffbBdxcbw:-Ku0aV4Unkffi1HTzpCX:bdju33i) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/5efec2ca646b26f13a9dd93be1fec3468b4f9a29/doppelganger/scripts/download_allocate_generate.py#L24)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

I should clarify, Alexei said we will want to employ segmentation for now at least. So I'm back to the original: 
`def person_segmenter(x): return x[inputs.AGE.name]`
</blockquote></details>

You can find this change on the `marginal-vehicles` branch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39)*

**Comment by katbusch** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/39#-:-Ku1C-0O4J-9S7NqDpI-:bnfp4nl)*

**Pull request merged**
