### PR TITLE
Run doppelganger on a state and puma

### PR DESCRIPTION
**Pull request by nikisix**
1. Download pums data from a database if necessary
2. Fetch census marginal data
3. Generate population and household data

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/34)

### CODE REVIEW

**Comment by alexeisw** [comment]
That'd be really useful to have some scripts, thanks for contributing, @nikisix !! 

The set of functions that scripts use should be properly documented too. The goal here is to enable reuse of the functions in multiple different scripts out of the context of the arguments and code in main().

Functions docstrings should also be detailed enough for anyone to use them without going into the actual package code to figure out what are the datatypes of all of the multiple inputs.

BTW, CircleCI builds fail on syntax, please investigate: 
./scripts/download_allocate_generate.py:90:44: E999 SyntaxError: invalid syntax
./scripts/fetch_puma_data_from_db.py:81:41: F821 undefined name 'unicode'

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-:-KsQ2SOFm9bquJFebjxi:b2iaykw)*

**Comment by katbusch** [comment]
+1 on documentation

We use the google python style guide for our commenting style: https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments

I'm also concerned that none of this is tested & we won't have a way of knowing if we break it

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/download_allocate_generate.py, line 51 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse-wM2GDyzPCd2_YPD:-Kse-wM2GDyzPCd2_YPE:b-8az78k) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L51)):*
> ```Python
>                         help='hostname of database with pums data', default='localhost')
>     parser.add_argument('--db_database', type=unicode, help='db name')
>     parser.add_argument('--db_schema', type=unicode, help='db schema', default='import')
> ```

I think you need to explain in more detail what this means since it's different for postgres vs mysql & could be confusing for some

---

*[scripts/download_allocate_generate.py, line 140 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse0z3c4a5DEelrIsfK:-Kse0z3c4a5DEelrIsfL:bvfsjfa) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L140)):*
> ```Python
> 
>     # Write the household bayes net to disk
>     def household_segmenter(x): x[inputs.NUM_PEOPLE.name]
> ```

A lambda would be nice here

---

*[scripts/fetch_puma_data_from_db.py, line 19 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse7gJ9QEyHnMnQU4jG:-Kse7gJ9QEyHnMnQU4jH:b-xmx7nt) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/fetch_puma_data_from_db.py#L19)):*
> ```Python
> 
> 
> def fetch_data(output_dir, state_id, puma_id, db_host, db_database, db_schema, db_user, db_password,
> ```

I don't think it's clear here that this write the data to a file.  I recommend doing the step of fetching & writing separately.  This can return a PumsData & the user can decide whether to write it out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-:-Kse6xuD9_HqtWrYErgb:b-8oa0c9)*

**Comment by nikisix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/download_allocate_generate.py, line 140 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse0z3c4a5DEelrIsfK:-KsebyTnl8oLSqMR7HjT:by16ipz) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L140)):*
> https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments
Had a lambda here for the segmenter function and the linter (flake8) made me turn it into a standard def-function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34)*

**Comment by nikisix** [comment]
*[scripts/download_allocate_generate.py, line 140 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse0z3c4a5DEelrIsfK:-KsedYd3ch20UE3arKrP:b-t3612p) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L140)):*
>  
Ups, please ignore the link there :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34)*

**Comment by katbusch** [comment]
Oh I forgot to mention: all of our files should have these lines at the top for python 3 compatibility:
```
from __future__ import (
    absolute_import, division, print_function, unicode_literals
)
```

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-:-KsekimM01eSGXHb5gwR:b-ag7ts5)*

**Comment by nikisix** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/download_allocate_generate.py, line 51 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse-wM2GDyzPCd2_YPD:-KsyZNs4Z5ZXV2SqkTj9:bjq2awu) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L51)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

I think you need to explain in more detail what this means since it's different for postgres vs mysql & could be confusing for some
</blockquote></details>

Good point, made it clear that the database in question is postgres.

---

*[scripts/fetch_puma_data_from_db.py, line 19 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse7gJ9QEyHnMnQU4jG:-KsyZiAX8vducNT2jnJq:b-ho5wpv) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/fetch_puma_data_from_db.py#L19)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

I don't think it's clear here that this write the data to a file.  I recommend doing the step of fetching & writing separately.  This can return a PumsData & the user can decide whether to write it out
</blockquote></details>

Agreed. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34)*

**Comment by katbusch** [comment]
Awesome, looking good!  Thanks for adding all those tests. Don't worry about the coverage decrease.  It's just because now the coverage tool knows our scripts exist :)

A couple small things remaining

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[setup.py, line 22 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIM5zCoIHE3-z-q9Sc:-KtIM5zCoIHE3-z-q9Sd:bdt6f6f) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/setup.py#L22)):*
> ```Python
>         'six>=1.10.0',
>         'future>=0.16.0',
>         # Circle-Ci AttributeError: module 'enum' has no attribute 'IntFlag'
> ```

Need to use enum34, not enum.  Not sure why that wasn't there!

---

*[setup.sh, line 1 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIMF7y34llWsf7SI46:-KtIMF7y34llWsf7SI47:bbr83dp) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/setup.sh#L1)):*
> ```Shell
> pip install numpy
> ```

Thanks for making this setup script!

---

*[setup.sh, line 5 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIMDJH3U10P0wwGnrT:-KtIMDJH3U10P0wwGnrU:b2gfhbj) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/setup.sh#L5)):*
> ```Shell
> pip uninstall -y pomegranate
> pip install pomegranate==0.7.1 --no-cache-dir
> pip install enum>=0.4.6
> ```

remove this line.

---

*[doppelganger/marginals.py, line 105 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIN4iaI5UYeSwkb0_8:-KtIN4iaI5UYeSwkb0_9:b5ty98d) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/doppelganger/marginals.py#L105)):*
> ```Python
> 
>             census_key (unicode): census API key
>             state (unicode): state fips code
> ```

What is fips?  Please write out what that is for the uninformed like me :)

---

*[doppelganger/marginals.py, line 106 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtINQm4lDf9Cfg6rlbK:-KtINQm4lDf9Cfg6rlbL:b-b3obc0) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/doppelganger/marginals.py#L106)):*
> ```Python
>             census_key (unicode): census API key
>             state (unicode): state fips code
>             pumas (iterable of unicode): a single puma or a list of pumas to fetch for.  If the
> ```

If it's a single PUMA, it should just be a list of one item.  Not need to special case this

---

*[test/test_download_allocate_generate.py, line 219 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIMQJ7bzztruFBFCWk:-KtIMQJ7bzztruFBFCWl:b-3rqfg9) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/test/test_download_allocate_generate.py#L219)):*
> ```Python
> 
>     @mock.patch('builtins.open')  # python 3 compatible
>     # @mock.patch('__builtin__.open')  # python 2 compatible
> ```

Remove unused line

---

*[scripts/download_allocate_generate.py, line 51 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse-wM2GDyzPCd2_YPD:-KtIOaqW8Lho5Q0q69HI:b-caticy) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L51)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

Good point, made it clear that the database in question is postgres.
</blockquote></details>

I don't think it's clear.  Can you change the help text for db schema to give a small explanation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-:-KtIPxB3AYv2evHAJqzL:bbd4553)*

**Comment by nikisix** [comment]
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[setup.sh, line 5 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIMDJH3U10P0wwGnrT:-KtIZph_KDpNm3JH3qNU:b7x8e6x) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/setup.sh#L5)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

remove this line.
</blockquote></details>

I actually stated out with it back in the setup.py, but that wasn't working so I moved it out and to the end, seems to work here. Changing to enum34.

---

*[scripts/download_allocate_generate.py, line 51 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-Kse-wM2GDyzPCd2_YPD:-KtIm7b77GQuYdXe1G3E:b-e6epqv) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/47b2fd512e83161a5eb3a6b8ac4436b6c3e2ccca/scripts/download_allocate_generate.py#L51)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

I don't think it's clear.  Can you change the help text for db schema to give a small explanation?
</blockquote></details>

Absolutely

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34)*

**Comment by nikisix** [comment]
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[setup.sh, line 1 at r9](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-KtIMF7y34llWsf7SI46:-KtImDOAqKwdV-agautf:b32vhw) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/ecd50a9cff37ceb5918185a04bd96a46c10bbd6d/setup.sh#L1)):*
<details><summary><i>Previously, katbusch (Kat Busch) wrote…</i></summary><blockquote>

Thanks for making this setup script!
</blockquote></details>

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34)*

**Comment by katbusch** [comment]
:lgtm:

Yay! Feel free to merge yourself once the tests pass

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/34#-:-KtJ2RloU-VZjC8YWcWO:b-c6d67j)*

**Pull request merged**
