### PR TITLE
Listbalacer update

### PR DESCRIPTION
**Pull request by nikisix**
Listbalancer edge-case fix. Logging update for parallel and longer runs.

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/doppelganger/38)

### CODE REVIEW

**Comment by kaelgreco** [comment]
Cool! nice work. a couple tiny things below, but looking good

---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[doppelganger/listbalancer.py, line 8 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN3Q8RyRhnUsO2pdbB:-KtN3Q8RyRhnUsO2pdbC:blnugco) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L8)):*
> ```Python
> import cvxpy as cvx
> import numpy as np
> import logging
> ```

pep8 nit:

"Imports should be grouped in the following order:
standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports."

---

*[doppelganger/listbalancer.py, line 171 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN1tlBxz8YpQlYZgbO:-KtN1tlBxz8YpQlYZgbP:bi2vtyg) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L171)):*
> ```Python
>                 break
>             mu = np.where(mu > 10, mu - 10, 1)
>             logging.info('Solver error encountered. Importance weights have been relaxed.')
> ```

This will get logged every loop that's unsolvable now

---

*[doppelganger/scripts/download_allocate_generate.py, line 112 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN7Vjj_WZOpuqKnD3t:-KtN7Vjj_WZOpuqKnD3u:bi8w5lw) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/scripts/download_allocate_generate.py#L112)):*
> ```Python
> 
>     if not os.path.exists(household_path) or not os.path.exists(person_path):
>         logging.info('Data not found at: \n{}\n or {}. Downloading data from the db'
> ```

I'd suggest doing old style string formatting for logging
`logging.info('This is an %s %s', 'info', 'message')`

["the logging package pre-dates newer formatting options such as str.format() and string.Template."](https://docs.python.org/2/howto/logging.html).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-:-KtN9KWszlpbTrc_Xf0U:b-olm41x)*

**Comment by nikisix** [comment]
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[doppelganger/listbalancer.py, line 171 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN1tlBxz8YpQlYZgbO:-KtPSDa97gzPIwSjzoNC:bgdohc4) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L171)):*
<details><summary><i>Previously, kaelgreco wrote…</i></summary><blockquote>

This will get logged every loop that's unsolvable now
</blockquote></details>

True. I didn't add this line in though (git blames me for it only because I removed a redundant newline from it). I can take it out or move it if you'd rather log in a different way?

---

*[doppelganger/scripts/download_allocate_generate.py, line 112 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN7Vjj_WZOpuqKnD3t:-KtPRpPl9hveqIpyIuLO:b3f6ced) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/scripts/download_allocate_generate.py#L112)):*
<details><summary><i>Previously, kaelgreco wrote…</i></summary><blockquote>

I'd suggest doing old style string formatting for logging
`logging.info('This is an %s %s', 'info', 'message')`

["the logging package pre-dates newer formatting options such as str.format() and string.Template."](https://docs.python.org/2/howto/logging.html).
</blockquote></details>

will do. is it weird that format works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38)*

**Comment by nikisix** [comment]
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[doppelganger/listbalancer.py, line 8 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN3Q8RyRhnUsO2pdbB:-KtPXzfd8mMVRlxb0OsP:b-p1bteq) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L8)):*
<details><summary><i>Previously, kaelgreco wrote…</i></summary><blockquote>

pep8 nit:

"Imports should be grouped in the following order:
standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports."
</blockquote></details>

Thanks for the tip!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38)*

**Comment by kaelgreco** [comment]
:lgtm:

---

Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/listbalancer.py, line 171 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN1tlBxz8YpQlYZgbO:-KtSBhpd2OSYXXjlIueT:b-ce9cwn) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L171)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

True. I didn't add this line in though (git blames me for it only because I removed a redundant newline from it). I can take it out or move it if you'd rather log in a different way?
</blockquote></details>

I think it's fine. we can see if it gets annoying in practice, but it seems useful.

---

*[doppelganger/scripts/download_allocate_generate.py, line 112 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN7Vjj_WZOpuqKnD3t:-KtSC0EOmZNZeu8fN4rw:bi1se6c) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/scripts/download_allocate_generate.py#L112)):*
<details><summary><i>Previously, nikisix (niki six) wrote…</i></summary><blockquote>

will do. is it weird that format works?
</blockquote></details>

yeah, it is weird! was news to me until recently

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-:-KtSCF9177o4ay-Nwybg:bnfp4nl)*

**Comment by nikisix** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doppelganger/listbalancer.py, line 171 at r1](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38#-KtN1tlBxz8YpQlYZgbO:-KtSCwmyQPogOPPvCAWs:b-3txfqt) ([raw file](https://github.com/sidewalklabs/doppelganger/blob/525d5494911cf13e7c005f6cee0eebfce5c8acfb/doppelganger/listbalancer.py#L171)):*
<details><summary><i>Previously, kaelgreco wrote…</i></summary><blockquote>

I think it's fine. we can see if it gets annoying in practice, but it seems useful.
</blockquote></details>

It's been useful in my runs so far to see which pumas need looser constraints than others.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/doppelganger/38)*

**Pull request merged**
